site_name: My Docs
site_description: ideas 
site_url: http://xiaochuany.github.io/b/ 

theme:
  name: material

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - search
  - blog:
      blog_toc: true
      archive_date_format: yyyy
      categories_allowed:
        - Tutorials
        - Notes
        - TIL
      pagination_per_page: 5
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
          short: true
  - tags:
      tags_file: tags.md
  - rss:
      match_path: "blog/posts/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated

extra:
  social:
    - icon: fontawesome/brands/linkedin
      name: xiaochuan on LinkedIn
      link: https://www.linkedin.com/in/xiaochuan-yang-088975188/
    - icon: fontawesome/brands/youtube
      name: xiaochuan on Youtube
      link: https://www.youtube.com/@xiaochuanyang
    - icon: fontawesome/brands/twitter
      name: xiaochuan on X
      link: https://x.com/xiaochuandev

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  # code block
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - js/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js